import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({style: ["normal"], weight: "500", subsets: ["devanagari"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  admin,
  team
}: Readonly<{
  children: React.ReactNode;
  admin: React.ReactNode;
  team: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        {children}
        <section className="w-[90%] mx-auto flex justify-center gap-5 items-center mt-10">
          {admin}
          {team}
      </section>
      </body>
    </html>
  );
}
